module.exports = [
    // --- WIN CONDITIONS ---
    { name: "montapuercos", type: "win_condition", cost: 4, counters: ["tornado", "cañon", "mini pekka", "torre tesla", "pescador"] },
    { name: "ariete de batalla", type: "win_condition", cost: 4, counters: ["electrocutadores", "tronco", "mago electrico", "lanzarrocas"] },
    { name: "montacarneros", type: "win_condition", cost: 5, counters: ["mago electrico", "zappies", "cañon"] },
    { name: "gigante noble", type: "win_condition", cost: 6, counters: ["pekka", "mini pekka", "barbaros de elite", "torre infernal"] },
    { name: "gigante", type: "win_condition", cost: 5, counters: ["torre infernal", "mini pekka", "bruja", "pekkka"] },
    { name: "gigante electrico", type: "win_condition", cost: 8, counters: ["torre infernal", "pekka", "mortero", "cañon"] },
    { name: "golem", type: "win_condition", cost: 8, counters: ["torre infernal", "pekka", "verdugo", "dragon infernal"] },
    { name: "golem de elixir", type: "win_condition", cost: 3, counters: ["valquiria", "mago", "verdugo", "torre bombarrera"] },
    { name: "sabueso de lava", type: "win_condition", cost: 7, counters: ["torre infernal", "dragon infernal", "verdugo", "mago"] },
    { name: "globo bombastico", type: "win_condition", cost: 5, counters: ["cohete", "mago", "mosquetera", "torre tesla", "cazador"] },
    { name: "barril de duendes", type: "win_condition", cost: 3, counters: ["tronco", "flechas", "bola de fuego"] },
    { name: "excavadora de duendes", type: "win_condition", cost: 4, counters: ["valquiria", "caballero oscuro", "mago"] },
    { name: "minero", type: "win_condition", cost: 3, counters: ["caballero", "guardias", "ejercito de esqueletos"] },
    { name: "cementerio", type: "win_condition", cost: 5, counters: ["veneno", "valquiria", "arqueras", "madre bruja"] },
    { name: "mortero", type: "win_condition", cost: 4, counters: ["lanzarrocas", "gigante", "golem"] },
    { name: "ballesta", type: "win_condition", cost: 6, counters: ["gigante", "golem", "terremoto", "cohete"] },
    { name: "rompemuros", type: "win_condition", cost: 2, counters: ["flechas", "tronco", "torre bombarrera"] },
    { name: "puercos reales", type: "win_condition", cost: 5, counters: ["bola de fuego", "valquiria", "mago", "torre bombarrera"] },
    { name: "barril de esqueletos", type: "win_condition", cost: 3, counters: ["zap", "flechas", "arquero magico"] },
    { name: "chispitas", type: "win_condition", cost: 6, counters: ["cohete", "mago electrico", "ejercito de esqueletos", "zap"] },

    // --- TANQUES Y MINI TANQUES ---
    { name: "mega caballero", type: "tank", cost: 7, counters: ["pekka", "torre infernal", "mini pekka", "caballero"] },
    { name: "pekka", type: "tank_killer", cost: 7, counters: ["ejercito de esqueletos", "torre infernal", "bruja", "guardias"] },
    { name: "mini pekka", type: "tank_killer", cost: 4, counters: ["ejercito de esqueletos", "guardias", "lanzadardos"] },
    { name: "valquiria", type: "mini_tank", cost: 4, counters: ["esbirros", "murcielagos", "principe"] },
    { name: "caballero", type: "mini_tank", cost: 3, counters: ["voladora", "pekkita"] },
    { name: "caballero dorado", type: "mini_tank", cost: 4, counters: ["pekka", "valquiria"] },
    { name: "principe", type: "mini_tank", cost: 5, counters: ["ejercito de esqueletos", "guardias", "lapida"] },
    { name: "principe oscuro", type: "mini_tank", cost: 4, counters: ["caballero", "valquiria"] },
    { name: "golem de hielo", type: "mini_tank", cost: 2, counters: [] },
    { name: "esqueleto gigante", type: "tank", cost: 6, counters: ["pekka", "torre infernal"] },
    { name: "duende gigante", type: "tank", cost: 6, counters: ["pekka", "torre infernal", "mini pekka"] },
    { name: "rey esqueleto", type: "tank", cost: 4, counters: ["valquiria", "caballero"] },
    { name: "monje", type: "tank", cost: 5, counters: ["pekka", "dragon infernal"] },
    { name: "leñador", type: "support_melee", cost: 4, counters: ["pekka", "valquiria"] },
    { name: "fantasma real", type: "support_melee", cost: 3, counters: ["caballero", "valquiria"] },
    { name: "bandida", type: "support_melee", cost: 3, counters: ["caballero", "guardias"] },
    { name: "pescador", type: "support_melee", cost: 3, counters: ["esbirros", "electrocutadores"] },
    { name: "minero poderoso", type: "tank_killer", cost: 4, counters: ["esbirros", "mago electrico"] },
    
    // --- SOPORTE A DISTANCIA ---
    { name: "mosquetera", type: "support", cost: 4, counters: ["bola de fuego", "rayo"] },
    { name: "trio de mosqueteras", type: "win_condition", cost: 9, counters: ["bola de fuego", "rayo", "cohete"] },
    { name: "mago", type: "support", cost: 5, counters: ["bola de fuego", "mini pekka"] },
    { name: "mago de hielo", type: "support", cost: 3, counters: ["bola de fuego", "mosquetera"] },
    { name: "mago electrico", type: "support", cost: 4, counters: ["bola de fuego", "mini pekka"] },
    { name: "bruja", type: "support", cost: 5, counters: ["valquiria", "rayo", "verdugo"] },
    { name: "bruja nocturna", type: "support", cost: 4, counters: ["verdugo", "mago"] },
    { name: "madre bruja", type: "support", cost: 4, counters: ["bola de fuego", "valquiria"] },
    { name: "arqueras", type: "support", cost: 3, counters: ["flechas", "tronco"] },
    { name: "lanzafuegos", type: "support", cost: 3, counters: ["flechas", "tronco"] },
    { name: "princesa", type: "support", cost: 3, counters: ["tronco", "flechas", "minero"] },
    { name: "duende lanzadardos", type: "support", cost: 3, counters: ["tronco", "flechas"] },
    { name: "arquero magico", type: "support", cost: 4, counters: ["bola de fuego"] },
    { name: "cazador", type: "tank_killer", cost: 4, counters: ["rayo", "mosquetera"] },
    { name: "verdugo", type: "support", cost: 5, counters: ["rayo", "mini pekka"] },
    { name: "lanzarrocas", type: "support", cost: 5, counters: ["esbirros", "inferno dragon"] },
    { name: "cañon con ruedas", type: "support", cost: 5, counters: ["valquiria", "esbirros"] },
    { name: "maquina voladora", type: "support", cost: 4, counters: ["bola de fuego"] },
    { name: "dragon electrico", type: "support", cost: 5, counters: ["bola de fuego", "rayo", "mago"] },
    { name: "bebe dragon", type: "support", cost: 4, counters: ["mosquetera", "mago electrico"] },
    { name: "dragon infernal", type: "tank_killer", cost: 4, counters: ["mago electrico", "esbirros", "rayo"] },
    { name: "esqueleto de los dragones", type: "support", cost: 4, counters: ["bola de fuego"] },
    { name: "fenix", type: "support", cost: 4, counters: ["mosquetera", "mago"] },
    { name: "reina arquera", type: "support", cost: 5, counters: ["rayo", "ejercito de esqueletos"] },
    { name: "principito", type: "support", cost: 3, counters: ["veneno", "bola de fuego"] },

    // --- SWARM (Tropas numerosas) ---
    { name: "ejercito de esqueletos", type: "swarm", cost: 3, counters: ["zap", "tronco", "valquiria"] },
    { name: "pandilla de duendes", type: "swarm", cost: 3, counters: ["tronco", "zap"] },
    { name: "duendes", type: "swarm", cost: 2, counters: ["zap", "tronco"] },
    { name: "duendes con lanza", type: "swarm", cost: 2, counters: ["zap", "tronco"] },
    { name: "esqueletos", type: "cycle", cost: 1, counters: [] },
    { name: "esbirros", type: "swarm", cost: 3, counters: ["flechas", "mago"] },
    { name: "horda de esbirros", type: "swarm", cost: 5, counters: ["flechas", "bola de fuego", "mago"] },
    { name: "murcielagos", type: "swarm", cost: 2, counters: ["zap", "bola de nieve"] },
    { name: "guardias", type: "swarm", cost: 3, counters: ["flechas"] },
    { name: "barbaros", type: "swarm", cost: 5, counters: ["bola de fuego", "mago", "bombardero"] },
    { name: "barbaros de elite", type: "tank_killer", cost: 6, counters: ["valquiria", "mega caballero", "pekka"] },
    { name: "pillos", type: "mini_tank", cost: 5, counters: ["tronco", "valquiria"] },
    { name: "reclutas reales", type: "swarm", cost: 7, counters: ["valquiria", "mago", "bombardero"] },
    
    // --- ESPIRITUS (Cycle) ---
    { name: "espiritu de hielo", type: "cycle", cost: 1, counters: [] },
    { name: "espiritu de fuego", type: "cycle", cost: 1, counters: [] },
    { name: "espiritu electrico", type: "cycle", cost: 1, counters: [] },
    { name: "espiritu sanador", type: "cycle", cost: 1, counters: [] },

    // --- ESTRUCTURAS ---
    { name: "cañon", type: "building", cost: 3, counters: [] },
    { name: "torre tesla", type: "building", cost: 4, counters: [] },
    { name: "torre infernal", type: "building", cost: 5, counters: [] },
    { name: "torre bombarrera", type: "building", cost: 4, counters: [] },
    { name: "lapida", type: "building", cost: 3, counters: [] },
    { name: "choza de duendes", type: "building", cost: 5, counters: ["terremoto", "veneno"] },
    { name: "choza de barbaros", type: "building", cost: 7, counters: ["terremoto", "veneno"] },
    { name: "horno", type: "building", cost: 4, counters: ["terremoto", "veneno"] },
    { name: "jaula del forzudo", type: "building", cost: 4, counters: [] },
    { name: "recolector de elixir", type: "building", cost: 6, counters: ["cohete", "minero", "bola de fuego"] },

    // --- HECHIZOS ---
    { name: "tronco", type: "spell", cost: 2, counters: [] },
    { name: "zap", type: "spell", cost: 2, counters: [] },
    { name: "bola de nieve", type: "spell", cost: 2, counters: [] },
    { name: "flechas", type: "spell", cost: 3, counters: [] },
    { name: "paquete real", type: "spell", cost: 3, counters: [] },
    { name: "barril de barbaro", type: "spell", cost: 2, counters: [] },
    { name: "tornado", type: "spell", cost: 3, counters: [] },
    { name: "terremoto", type: "spell", cost: 3, counters: [] },
    { name: "bola de fuego", type: "spell", cost: 4, counters: [] },
    { name: "veneno", type: "spell", cost: 4, counters: [] },
    { name: "rayo", type: "spell", cost: 6, counters: [] },
    { name: "cohete", type: "spell", cost: 6, counters: [] },
    { name: "hielo", type: "spell", cost: 4, counters: [] },
    { name: "furia", type: "spell", cost: 2, counters: [] },
    { name: "clon", type: "spell", cost: 3, counters: [] },
    { name: "espejo", type: "spell", cost: 0, counters: [] },
    { name: "vacio", type: "spell", cost: 3, counters: [] }
];
